[tool.poetry]
name = "tasca-3"
version = "0.1.0"
description = ""
authors = ["Miguel Ángel Vílchez López <mangel@matronica.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
